### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Diison** [termMed/rf2-to-owl#3]
hi, I ran the jarfile, but got the exception like:

---------------------------------------------------
(base) sh-4.2$ java -jar rf2-to-owl-0.0.4.jar -mode rf2-to-owl -rf2Folder /home/s2020017/work/snomed-owl-toolkit/SNOMED_CT/SnomedCT_InternationalRF2_PRODUCTION_20200731T120000Z/Snapshot -output ontology.owl
log4j:WARN No appenders could be found for logger (com.termmed.owl.util.FileHelper).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.NullPointerException
        at java.io.File.<init>(File.java:277)
        at com.termmed.owl.RF2Parser.parse(RF2Parser.java:235)
        at com.termmed.owl.Runner.main(Runner.java:81)
---------------------------------------------------

Could you help me to solve it? Thank you so much!

**Comment by wgehring-ml** [comment]
I am also encountering this same error
